workspace:
  type: Workspace2D
  parameters:
    limits:
      - [0.0, 10.0]
      - [0.0, 10.0]

    obstacles:
      - type: Rectangle
        parameters:
          xlim: [2.3, 3.4]
          ylim: [7, 9.8]

      - type: Rectangle
        parameters:
          xlim: [7.3, 8.5]
          ylim: [7.6, 10]

      - type: Rectangle
        parameters:
          xlim: [1.3, 3]
          ylim: [2.8, 3.8]

      - type: Polygon
        parameters:
          p_in:
            - [5, 0.9]
            - [7.1, 0.9]
            - [7.1, 3.7]

robot:
  type: Robot2D
  parameters:
    pos: [5.0, 5.0]
    footprint: [[0.1, 0.01], [-0.1, 0.01], [-0.1, -0.01], [0.1, -0.01]]

planning:
  start: [5.0, 5.0]
  goal:  [9.5, 9.5]